timestamp = "Mon May 29 13:52:16 2017"
tags = ["testing", "should handle extra whitespace in tags", "nonsense"]
content = "Now the tags get trimmed.\nThat'll probably help a bit with searching at some point.\nNot sure why I always do three lines for this thing?\n"
